### ISSUE TITLE
Clarifying Instructions

### ISSUE THREAD

**Issue by ProfessorPeregrine** [zarathucorp/shiny-electron-template-windows#4]
I am an absolute beginner with this and so many of the steps are unclear to me. I really appreciate the work to keep this alive as it will be of a great service to me and my students, if I can get it to work. As far as I have been able to find, it is the only currently maintained way to get a Shiny app to run with electron.

Hopefully my confusion might help out the next beginner.

At this point, I cannot get the R Shiny app to work in electron app. The R Shiny app works in RStudio and RGui, though it is a rather big and complicated one.

There are a few things I think I can correct to make it easier for others like me to understand, some of which are just English language changes. I find when I am working with something that is very unfamiliar, even small language improvements help a lot.

There are others things I don't understand what to do.

---

### Suggestions to make it more understandable:

- Step 4, I think in Windows this should be: `npm install --save-dev @electron-forge/cli`
- Step 8, I think this is a carry over from the Mac version. Change **In your project directory (may Github/shiny-electron-template-m1),** ... to **In your project directory (perhaps Github/shiny-electron-template-windows),** ...

- Step 10, ...**`get-r-win.sh`: For install local R for electron app.** I think a better way to say that would be something like this: "**`get-r-win.sh`: This installs a local R that will be used by the electron app. You may need to edit `get-r-in.sh` so that the URL after curl is a link to the same R version that you have installed on your computer.** Or this could be added to Step 12.

Also in Step 10:
**Folder shiny from this template, containing:

    shiny/app.R: THIS IS YOUR SHINY APP'S CODE**

could be clearer as:

**Folder shiny from this template, then replace shiny/app.R with your app's code and include any other files your app needs like a /www folder here.**

---

### Questions/Clarifications:

- Is there anything that needs to change in src/main.js to make it run?

For Steps 16 and 17, I have a lot of questions. 

- Primarily around do I REPLACE the content of the two files or MERGE their content? And if merging, specifically what do I need to change and leave in place?

For forge-config.js, the one that was built already had
```
    {
      name: '@electron-forge/maker-zip',
      platforms: ['darwin'],
    },
```
Should I replace this with the version in [fix] that says
```
    {
      name: '@electron-forge/maker-zip'     
    }
```

- Do I delete the other makers?

In the one created by electron, forge-config had a lot of other things in it other than makers, do I leave them in?

On to package.json...

- Again, do I merge what is in [fix] package.json into the one that was created, or replace it?

- Do I keep the version numbers in [fix] package.json or update them? If I need to update them, it would be helpful to have a step to do that and to know about www.npmjs.com to get the current versions there.

- In step 19 it says to type electron-forge start - I almost got something to run when I typed npm start, but I only ever got errors when I typed electron-forge start. One error was "You must depend on "electron-prebuilt-compile" in your devDependencies" which is deprecated I guess? I think either it should be in [fix] package.json or I am doing something wrong.

There are too many things I don't know, so I am just randomly trying things, and that is not likely to succeed! So thanks in advance for any help you can give!

**Comment by jhk0530** [comment]
Hi @ProfessorPeregrine, thanks for let me know. 

First, I edited markdown to read easier.
and I'll try to answer / update it.

**Comment by jhk0530** [comment]
### Step 4
- `npm i -g @electron-forge/cli` still works fine for me, but I'll mention `npm install --save-dev @electron-forge/cli`.

### Step 8
- Yes, it was typo and I fixed it. 👍🏻 

### Step 10
- I updated it.

--

## Questions

> Is there anything that needs to change in src/main.js to make it run?

No. you can run it without change from template's `src/main.js`. but if you want customize electron, you may check it

> For Steps 16 and 17, I have a lot of questions. Primarily around do I REPLACE the content of the two files or MERGE their content? And if merging, specifically what do I need to change and leave in place?

No. you have to **replace**, not merge. since node / npm and all Javascript library is constantly being updated and adding things I don't know about and don't need. Although I update it from time to time, I have created a stable version to avoid errors and recommend using it.

> Do I delete the other makers?

Yes, but not required. because I expected to use only ZIP. so I think other makers unnecessary and removed it. but you can include it. 

> In the one created by electron, forge-config had a lot of other things in it other than makers, do I leave them in?

Same with above, replace it with template's. 

> Again, do I merge what is in [fix] package.json into the one that was created, or replace it?

replace it.

> Do I keep the version numbers in [fix] package.json or update them? If I need to update them, it would be helpful to have a step to do that and to know about [www.npmjs.com](http://www.npmjs.com/) to get the current versions there.

No. you should not update them. Especially axios.

> In step 19 it says to type electron-forge start - I almost got something to run when I typed npm start, but I only ever got errors when I typed electron-forge start. One error was "You must depend on "electron-prebuilt-compile" in your devDependencies" which is deprecated I guess? I think either it should be in [fix] package.json or I am doing something wrong.

I think this should be separated with another issue. 
Please try again with updated guide. and if you have still problem, 
raise a issue with attatched screenshot.

Thanks

**Comment by ProfessorPeregrine** [comment]
You are amazing! Thanks for this! Opening new issue on prebuilt...
